### PR TITLE
Code deduplication, new comment format (comments-example.txt).

### PR DESCRIPTION
**Pull request by wunderfeyd**
Hi,

I started to play around a little bit. But had to drop the old comments format, to add new features in the next days/weeks. Let me know what you think about this.

### CODE REVIEW

**Comment by ghost** [comment]
I merge it and try it out later. Thanks!

btw: you can drop, what you want :)

**Comment by wunderfeyd** [comment]
Yeah, but it could be work for your website to convert these if you use the newer plugin. Okay, I'll go ahead. Thanks for merging.

**Comment by wunderfeyd** [comment]
> Great work. Would it be possible to have something like URL: in the comments file. for linking to the author?

Yes, I'll add this now. Also I'll try to add the comment directly from the comment-contact page, but it's disabled until you enable it.

> One other thing. The getCommentCount() is not working in content-blogpages.php. I had to use

Okay, thanks. I'll look into this.

**Comment by wunderfeyd** [comment]
Could you upload your blogpages.php please? :)

**Comment by ghost** [comment]
Sure: 

https://github.com/nasendackel/YellowComments/blob/master/content-blogpages.php

**Comment by wunderfeyd** [comment]
Thanks, I'll create a new pull request tomorrow.

**Pull request merged**
