### PR TITLE
Automatic append of comments (hidden), call from blogpages.php and Ur…

### PR DESCRIPTION
**Pull request by wunderfeyd**
…l display.

Hi,

I continued. This time I merged the commentcontact.php into the comment.php. Comments can be stored directly to file also (commentsAutoAppend setting) and if file permissions allow these operations. Please test, since I had no valid working sendmail on my local setup.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks a lot. I will test in my test installation

**Comment by ghost** [comment]
Sendmail is not working, I will do a deeper test tomorrow. Thanks a lot for the work!

**Comment by wunderfeyd** [comment]
Thanks for testing and correction. The code is still not in it's final state. There are some things in my head which were nice to have. Maybe I should file issues/suggestion for every feature/change? What do you think?

**Comment by ghost** [comment]
Is there a way in github to add you as administrator for this repo? Then I don't have to approve every feature :)

**Comment by wunderfeyd** [comment]
Yes. Repository settings -> Collaborators -> Name.

**Comment by ghost** [comment]
Done :)

**Comment by wunderfeyd** [comment]
Thanks. :)

**Pull request merged**
